# 使用Scikit-Learn 完成預測
### Scikit-Learn在三個面向提供支援。
1. 獲取資料:***klearn.datasets***
2. 掌握資料:***sklearn.preprocessing*** 
3. 機器學習:***sklearn Estimator API*** 

獲取資料的方式有很多種（包含檔案、資料庫、網路爬蟲、Kaggle Datasets等），<br>
其中最簡單的方式是從Sklearn import 內建的資料庫。由於其特性隨手可得且不用下載，所以我們通常叫他**玩具資料**：

# 基本架構

* 讀取資料&pre-processing
* 切分訓練集與測試集 
* 模型配適
* 預測 
* 評估(計算成績可能是誤差值或正確率或..)


In [2]:
%matplotlib inline

from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


## 讀取Iris資料集與資料前處理

Iris Flowers 資料集

我們在這個項目中使用 Iris Data Set，這個資料集中的每個樣本有4個特徵，1個類別。該資料集1中的樣本類別數為3類，每類樣本數目為50個，總共150個樣本。

屬性資訊：

    花萼長度 sepal length(cm)
    花萼寬度 sepal width(cm)
    花瓣長度 petal length(cm)
    花瓣寬度 petal width(cm)
    類別：
        Iris Setosa
        Iris Versicolour
        Iris Virginica

樣本特徵資料是數值型的，而且單位都相同（釐米）。

![Iris Flowers](images/iris_data.PNG)


In [4]:
iris = datasets.load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

* 印出iris的key值與檔案位置
* 查看前10筆資料
* 查看資料型別
* 印出標註的樣本類別資料

In [6]:
print(iris.keys())

print(iris['filename'])

print(iris.data[0:10])

print(type(iris.data))

print(iris.target_names)

print(iris.target)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
iris.csv
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
<class 'numpy.ndarray'>
['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
# we only take the first two features. 
X =iris.data[:,:2]
print(X.shape)
Y =iris.target
print(Y.shape)


(150, 2)
(150,)


In [8]:
#以下是組成 pandas DataFrame (也可以不用這種做)
x = pd.DataFrame(iris.data, columns=iris['feature_names'])
x.head(10)


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

In [9]:
#建立Target欄位與資料
y = pd.DataFrame(iris['target'], columns=['target'])

# 顯示前五筆資料
y.head()

# 正確地印出 target_names- 將數字轉變成花名
print("target_names: " + str(iris['target_names']))

target_names: ['setosa' 'versicolor' 'virginica']


In [10]:
#合併資料特徵欄位與目標欄位
iris_data=pd.concat([x,y],axis=1)
iris_data.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       0  
8       0  
9       0

In [11]:
#只選擇目標為0與1的資料
iris_data = iris_data[iris_data['target'].isin([0, 1])]
print(iris['data'].size)
iris_data


600


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

## 切分訓練集與測試集
> train_test_split()

In [53]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(iris_data[['sepal length (cm)', 'petal length (cm)']], iris_data['target'], test_size=0.2)

In [55]:
X_train.head()

sepal length (cm)  petal length (cm)
15                5.7                1.5
22                4.6                1.0
63                6.1                4.7
8                 4.4                1.4
70                5.9                4.8

In [57]:
X_train.shape

(80, 2)

In [59]:
X_test.head()

sepal length (cm)  petal length (cm)
83                6.0                5.1
82                5.8                3.9
91                6.1                4.6
38                4.4                1.3
61                5.9                4.2

In [61]:
X_test.shape

(20, 2)

In [63]:
Y_train.head()

15    0
22    0
63    1
8     0
70    1
Name: target, dtype: int32

In [65]:
Y_test.head()

83    1
82    1
91    1
38    0
61    1
Name: target, dtype: int32

# Appendix 

>normalization和standardization是差不多的<br>
都是把數據進行前處理，從而使數值都落入到統一的數值範圍，從而在建模過程中，各個特徵量沒差別對待。<br> 
* normalization一般是把數據限定在需要的範圍，比如一般都是【0，1】，從而消除了數據量綱對建模的影響。<br> 
* standardization 一般是指將數據正態化，使平均值0方差為1.<br> 

因此normalization和standardization 是針對數據而言的，消除一些數值差異帶來的特種重要性偏見。<br>
經過歸一化的數據，能加快訓練速度，促進算法的收斂。

### Standardization (z-score)
    to compute the mean and standard deviation on a training set so as to be able to later reapply the same transformation on the testing set. 

In [90]:
# 定義 norm_stats
def norm_stats(dfs):  
    minimum = dfs.min(axis=0)  # 計算每列的最小值
    maximum = dfs.max(axis=0)  # 計算每列的最大值
    mu = dfs.mean(axis=0)      # 計算每列的均值
    sigma = dfs.std(axis=0)    # 計算每列的標準差
    return minimum, maximum, mu, sigma  # 返回 Series，而不是 scalar

# 定義 z_score
def z_score(col, stats):  
    _, _, mu, s = stats  
    return (col - mu) / s  # Pandas 直接支援 DataFrame 運算

# 計算統計數據並進行標準化
stats = norm_stats(X_train)
arr_x_train = np.array(z_score(X_train, stats))
arr_y_train = np.array(Y_train)
arr_x_train[:5]

stats = norm_stats(X_test)
arr_x_test = np.array(z_score(X_test, stats))
arr_y_test = np.array(Y_test)
arr_x_test[:5]

array([[ 1.20775527,  1.82505934],
       [ 0.88352567,  1.00017376],
       [ 1.36987007,  1.48135702],
       [-1.38608155, -0.78707832],
       [ 1.04564047,  1.20639516]])

## use sklearn

In [92]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(X_train)  #Compute the statistics to be used for later scaling.
print(sc.mean_)  #mean
print(sc.scale_) #standard deviation

[5.525 2.965]
[0.63610141 1.42951915]


In [94]:
#transform: (x-u)/std.
X_train_std = sc.transform(X_train)
X_train_std[:5]

array([[ 0.27511337, -1.02482013],
       [-1.45417066, -1.37458809],
       [ 0.90394392,  1.21369483],
       [-1.76858593, -1.09477372],
       [ 0.58952864,  1.28364842]])

The scaler instance can then be used on new data to transform it the same way it did on the training set:

In [97]:
X_test_std = sc.transform(X_test)
print(X_test_std[:10])

[[ 0.74673628  1.4935092 ]
 [ 0.43232101  0.65406609]
 [ 0.90394392  1.14374124]
 [-1.76858593 -1.16472731]
 [ 0.58952864  0.86392687]
 [ 0.27511337  0.86392687]
 [-0.66813246 -1.02482013]
 [ 1.37556684  1.07378764]
 [-1.92579357 -1.3046345 ]
 [-0.19650955 -1.02482013]]


you can also use fit_transform method (i.e., fit and then transform)    

In [107]:
X_train_std = sc.fit_transform(X_train)  
X_test_std = sc.fit_transform(X_test)
print(X_test_std[:10])


[[ 1.23913076  1.87247137]
 [ 0.90647821  1.02615663]
 [ 1.40545704  1.51984023]
 [-1.42208967 -0.80752532]
 [ 1.07280449  1.23773531]
 [ 0.74015193  1.23773531]
 [-0.25780573 -0.66647286]
 [ 1.90443587  1.449314  ]
 [-1.58841595 -0.94857778]
 [ 0.2411731  -0.66647286]]


In [111]:
print('mean of X_train_std:',np.round(X_train_std.mean(),4))
print('std of X_train_std:',X_train_std.std())

mean of X_train_std: -0.0
std of X_train_std: 1.0


## Min-Max Normaliaztion
    Transforms features by scaling each feature to a given range.
    The transformation is given by:

    X' = X - X.min(axis=0) / ((X.max(axis=0) - X.min(axis=0))
    X -> N 維資料
    


In [114]:
x1 = np.random.normal(50, 6, 100)  # np.random.normal(mu,sigma,size))
y1 = np.random.normal(5, 0.5, 100)

x2 = np.random.normal(30,6,100)
y2 = np.random.normal(4,0.5,100)
plt.scatter(x1,y1,c='b',marker='s',s=20,alpha=0.8)
plt.scatter(x2,y2,c='r', marker='^', s=20, alpha=0.8)

print(np.sum(x1)/len(x1))
print(np.sum(x2)/len(x2))

50.0884133514525
29.361914560904506


In [116]:
x_val = np.concatenate((x1,x2))
y_val = np.concatenate((y1,y2))

x_val.shape

(200,)

In [118]:
def minmax_norm(X):
    return (X - X.min(axis=0)) / ((X.max(axis=0) - X.min(axis=0)))

In [120]:
minmax_norm(x_val[:10])

array([1.        , 0.46654411, 0.62566267, 0.74320568, 0.58909938,
       0.43167358, 0.4176812 , 0.68337431, 0.        , 0.40692269])

In [122]:
from sklearn.preprocessing import MinMaxScaler
x_val=x_val.reshape(-1, 1) #1d to 2d
scaler = MinMaxScaler().fit(x_val)  # default range 0~1
print(scaler.data_max_)
print(scaler.transform(x_val)[:10])

[62.91282385]
[[0.97418797]
 [0.68223816]
 [0.76932058]
 [0.83364954]
 [0.74931022]
 [0.66315421]
 [0.65549646]
 [0.80090502]
 [0.42690784]
 [0.64960854]]
